export const INITIAL_VEHICLES = [
  {
    id: 'veh-1',
    registrationNumber: 'MH-12-GQ-4819',
    model: 'Tata Prima 5530.S',
    type: 'Heavy Truck',
    capacity: 25000,
    odometer: 142050,
    cost: 45000,
    status: 'AVAILABLE',
  },
  {
    id: 'veh-2',
    registrationNumber: 'DL-01-AX-9922',
    model: 'Mahindra Bolero Maxi',
    type: 'Light Cargo',
    capacity: 1500,
    odometer: 89300,
    cost: 15000,
    status: 'ON_TRIP',
  },
  {
    id: 'veh-3',
    registrationNumber: 'KA-03-MP-3311',
    model: 'Ashok Leyland Dost+',
    type: 'Delivery Van',
    capacity: 2000,
    odometer: 64120,
    cost: 12500,
    status: 'IN_SHOP',
  },
  {
    id: 'veh-4',
    registrationNumber: 'MH-14-EU-0815',
    model: 'Eicher Pro 3015',
    type: 'Heavy Truck',
    capacity: 15000,
    odometer: 198700,
    cost: 32000,
    status: 'AVAILABLE',
  },
  {
    id: 'veh-5',
    registrationNumber: 'DL-03-BY-7788',
    model: 'Tata Ace Gold EV',
    type: 'Electric Van',
    capacity: 600,
    odometer: 12400,
    cost: 8500,
    status: 'AVAILABLE',
  },
  {
    id: 'veh-6',
    registrationNumber: 'KA-05-ZR-4920',
    model: 'Volvo FMX 460',
    type: 'Heavy Truck',
    capacity: 32000,
    odometer: 256800,
    cost: 89000,
    status: 'RETIRED',
  },
  {
    id: 'veh-7',
    registrationNumber: 'HR-26-CK-1234',
    model: 'Force Traveler Delivery',
    type: 'Delivery Van',
    capacity: 3500,
    odometer: 48900,
    cost: 18000,
    status: 'ON_TRIP',
  },
];

export const INITIAL_DRIVERS = [
  {
    id: 'drv-1',
    name: 'Alex Driver',
    licenseNumber: 'DL-MH1220150098',
    licenseCategory: 'Heavy Vehicle (Class A)',
    licenseExpiry: '2027-08-15',
    phone: '+91 98765 43210',
    safetyScore: 94,
    status: 'AVAILABLE',
  },
  {
    id: 'drv-2',
    name: 'Suresh Kumar',
    licenseNumber: 'DL-KA0320180245',
    licenseCategory: 'Light Vehicle (Class B)',
    licenseExpiry: '2026-11-20',
    phone: '+91 87654 32109',
    safetyScore: 88,
    status: 'ON_TRIP',
  },
  {
    id: 'drv-3',
    name: 'Vijay Shinde',
    licenseNumber: 'DL-DL0120120876',
    licenseCategory: 'Heavy Vehicle (Class A)',
    licenseExpiry: '2026-06-10', // Expired!
    phone: '+91 76543 21098',
    safetyScore: 72,
    status: 'OFF_DUTY',
  },
  {
    id: 'drv-4',
    name: 'Rajesh Sharma',
    licenseNumber: 'DL-MH1420200456',
    licenseCategory: 'Heavy Vehicle (Class A)',
    licenseExpiry: '2028-12-05',
    phone: '+91 95432 10987',
    safetyScore: 96,
    status: 'AVAILABLE',
  },
  {
    id: 'drv-5',
    name: 'Amit Patel',
    licenseNumber: 'DL-HR2620210012',
    licenseCategory: 'Light Vehicle (Class B)',
    licenseExpiry: '2029-03-22',
    phone: '+91 91234 56789',
    safetyScore: 65,
    status: 'SUSPENDED',
  },
];

export const RECENT_TRIPS = [
  {
    id: 'trip-101',
    vehicleNo: 'MH-12-GQ-4819',
    driverName: 'Alex Driver',
    source: 'Pune Logistics Hub',
    destination: 'Mumbai Port Term 2',
    cargoWeight: 18000,
    plannedDistance: 150,
    status: 'COMPLETED',
  },
  {
    id: 'trip-102',
    vehicleNo: 'DL-01-AX-9922',
    driverName: 'Suresh Kumar',
    source: 'Delhi Warehouse A',
    destination: 'Jaipur Distribution Hub',
    cargoWeight: 1200,
    plannedDistance: 270,
    status: 'DISPATCHED',
  },
  {
    id: 'trip-103',
    vehicleNo: 'HR-26-CK-1234',
    driverName: 'Vijay Shinde',
    source: 'Gurugram Facility',
    destination: 'Chandigarh Hub',
    cargoWeight: 3100,
    plannedDistance: 245,
    status: 'DISPATCHED',
  },
  {
    id: 'trip-104',
    vehicleNo: 'MH-14-EU-0815',
    driverName: 'Rajesh Sharma',
    source: 'Nashik Depot',
    destination: 'Mumbai Port Term 2',
    cargoWeight: 14200,
    plannedDistance: 180,
    status: 'COMPLETED',
  },
  {
    id: 'trip-105',
    vehicleNo: 'DL-03-BY-7788',
    driverName: 'Rajesh Sharma',
    source: 'Delhi Warehouse B',
    destination: 'Noida Center',
    cargoWeight: 500,
    plannedDistance: 45,
    status: 'DRAFT',
  },
];

export const CHART_UTILIZATION = [
  { name: 'Mon', utilization: 72 },
  { name: 'Tue', utilization: 78 },
  { name: 'Wed', utilization: 85 },
  { name: 'Thu', utilization: 82 },
  { name: 'Fri', utilization: 88 },
  { name: 'Sat', utilization: 92 },
  { name: 'Sun', utilization: 80 },
];
